### ISSUE TITLE
'this' does not contain validated form values in action callback

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#10]
When using `data=` to setup initial form values, `this` of the `action` callback contains those initial values instead of the new validated values.

This issue does not occur when not using `data=`.

A workaround is to use the `els` argument to get the value from the DOM:
```
        return function(els, callbacks) {
            var fields = {};
            els.forEach(function(el)
                {
                var $el = $(el);
                var name = $el.attr('name');
                check(name, String);
                fields[name] = $el.val();
                });

            // Here 'this' contains the old values and 'fields' contains the new ones
            ...
        }
```

**Comment by jonjamz** [comment]
Thanks for the workaround. I will fix this ASAP.

**Comment by jonjamz** [comment]
Just want to confirm--does this happen when you've made changes to the form elements that passed validation?

**Comment by steph643** [comment]
I cannot reproduce the issue! Please let me check.

**Comment by steph643** [comment]
Got it: the issue occurs when I change the value programatically (using `$element.val(newValue)`). The issue does not occur when changing the value manually (normal case).
My mistake is that I expected the package to behave the same way when changing values manually and programatically.

**Comment by steph643** [comment]
I will add a feature request for a function to change values programatically :-)

**Comment by jonjamz** [comment]
When you register an element, the validationEvent is what triggers the change. So you can probably pull it off just by triggering that event on the element with the ".reactive-element" class with jQuery after the update.

**Comment by steph643** [comment]
Your suggestion works like a charm, thanks a lot!
