### ISSUE TITLE
Feature request: knowing if a value has change from within the action callback

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#11]
From within element and block template helpers, the `{{changed}}` variable indicates when a value has successfully been changed.

It would be great to get this information from within the `action` callback also, avoiding the need for manual comparison of the original and new values before updating the database.

**Comment by jonjamz** [comment]
Good idea.

**Comment by jonjamz** [comment]
What if, when passing in initial data, the action function's `this` only contained the fields that have changed?

**Comment by steph643** [comment]
That would fit perfectly with my use case: upon submit, I call Collection.update() with the changed values.

There might be cases where having all values would be useful, but I can't find one right now...

By the way: I don't like using 'this' and I would prefer the values to be the first parameter of the action function (self-documented, easier to explain in the doc, easier to remember). However, I have to say I am not much of a Javascript guy, so I'll probably never understand what is so nice about this floating 'this' :-)

**Comment by jonjamz** [comment]
I thought about whether to use `this` and ended up doing it because:

1. It would avoid a breaking change.
2. It's similar to the data context you find in Meteor's event handlers.

**Comment by jonjamz** [comment]
What I've decided to do here is leave `this` as the entire form data context (including initial data if unchanged) and pass an object containing only changed fields as the third argument into the action function.
