### ISSUE TITLE
Terminology inconsistency: form vs. "form block"

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#18]
In the following code, `myFormBlock` is a ***form block*** and `myForm` is a ***form***:

```html
<template name="myFormBlock">
  <form>
    {{> UI.contentBlock
        data=data
        schema=schema
        schemaContext=__schemaContext__
        setValidatedValue=__setValidatedValue__
        submit=__submit__
        submitted=__submitted__
        loading=__loading__
        failed=__failed__
        success=__success__
    }}
		<p>
		  <button type="submit" disabled="{{#if invalidCount}}disabled{{/if}}">Submit</button>
		</p>	
  </form>
</template>

<template name="myForm">
    {{#myFormBlock schema=schema action=action}}		
      {{> myInput field='testField1'}}
      {{> myInput field='testField2'}}
      {{> myInput field='testField3'}}
    {{/myFormBlock}}
</template>
```

A form is, well, a form. A form block is a "container that controls workflow and handles submission". 

As long as there is no way to avoid explicitly managing form blocks (see discussion https://github.com/meteortemplates/forms/issues/15), it is important not to mix up the two concepts.

The issue is that there are many places in the API and documentation where both terms are mixed up. See for example `basicForm`, which is really a basic form block! Or `createForm`, which actually creates a form block!

**Comment by steph643** [comment]
I am not so enthusiastic about the term *form block*, which I find basically meaningless. Nothing closer to a "container that controls workflow and handles submission"?

I would prefer `registerElement` and `registerFormBlock` over `createElement` and `createFormBlock`. From a user perspective, those 2 functions do not create anything...

**Comment by jonjamz** [comment]
I tend to agree with you on this. A *form block* is named that way because it's a *block helper* in Blaze terminology. 

I'm open to suggestions on better names, although I feel like that is still semantically correct as a name.

**Comment by jonjamz** [comment]
I can re-write the docs to call it a *form* which would avoid a breaking change.

**Comment by steph643** [comment]
Ah, I didn't see the relationship with Blaze *block helpers* (terrible term, by the way). I now see that *form block* makes some sense. 

Some other ideas (from a non-native English speaker): elementContainer, elementGroup, formStatus, formState, formAutomaton, formMachine, formWorkflow, formProcessing.

-----------

I don't think it would be good to use *form* for *form block*. To me, the *form* is really the place where you assemble elements (see the template named "myForm" in the sample code above).

To not break compatibility, you can just add a `createFormBlock` function and let `createForm` with a "deprecated" warning.

**Comment by jonjamz** [comment]
Definitely--I'll opt for `createFormBlock` for now. I like formWorkflow the best out of your suggestions. Other options I can think of are formContainer and formContext.

If I don't have "form" in there somewhere, I fear the related terminology might get lost. For example, a container doesn't usually have an action, but a form does.

**Comment by steph643** [comment]
Ok, makes sense.

I will allow myself to post more ideas here, in case this rings a bell on your side.

formAction, formActions, formReaction, formResponse, formBehavior, formEvents, formEffect, formEffects, formFX, formInMotion, formPower, formLeader, formHead, formBoss, formManager, formChief, formGears, formCog

**Comment by jonjamz** [comment]
We can change this to `registerFormBlock
