### ISSUE TITLE
atmosphere package throws an error on add

### ISSUE THREAD

**Issue by meteorpoly** [meteortemplates/forms#25]
$ meteor add templates:forms
 => Errors while adding packages:             
                                              
While downloading templates:forms@1.10.0...:
error: getaddrinfo ENOTFOUND

**Comment by jonjamz** [comment]
Hi,

I am unable to reproduce this error. Running `meteor add templates:forms` works for me to get `1.10.0`. 
Have you been able to successfully add other packages at the same time as this one failed?

Also, what version of Meteor are you running?

Thanks

**Comment by meteorpoly** [comment]
Issue resolved after reboot... I'm using latest version of Meteor with 10 other packages which worked fine. Thanks
