### ISSUE TITLE
Feature request: form block accepting no schema

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#27]
It seems the package works as expected with an empty schema (no validation). It would be useful (especially for debugging) that a form block can be created without a schema at all.

If it is decided that there **must** be a schema, then maybe error messages should be improved. Here are the various error messages you can get:
* No argument to form block: `Uncaught TypeError: Cannot read property 'schema' of null`
* Only the `data` argument: `Uncaught Error: Match error: Expected Function`
* Only the `action` argument, or both `action` and `data`: `Uncaught TypeError: Cannot read property 'invalidKeys' of undefined`

**Comment by jonjamz** [comment]
Form blocks should work without a schema as-is, and the helpers relating to schema should fall back to `true` or `false` depending on the helper. I'll have to double-check. But you can override helpers on elements in the template invocation like `{{> basicInput submitted=true}}` if you need to use something standalone.

**Comment by jonjamz** [comment]
Those error messages are pretty bad, I agree. The message should clearly state what's missing. Perhaps I should change the checks from `check` to `Match.test` and throw custom errors.

**Comment by jonjamz** [comment]
I added this recently and it may have caused a regression that throws an error when no schema is defined. Is this what you're talking about when you say a schema of some sort is required?

https://github.com/meteortemplates/forms/blob/master/lib/module.coffee#L233-L234

**Comment by steph643** [comment]
Here is the status after your fix:
* No argument to form block: `Uncaught TypeError: Cannot read property 'schema' of null`
* Only the `data` argument: `Uncaught Error: [[forms] The action function is missing or invalid in your Form Block. This is a required field--you can't submit your form without it.]`
* Only the `action` argument, or both `action` and `data`: `Uncaught TypeError: Cannot read property 'invalidKeys' of undefined`

So case 2 is much better, but cases 1 and 3 remain.

I am wondering: why do you wa

**Comment by jonjamz** [comment]
Oh ok, I don't think I tested without the arguments actually, only with incorrect values.

I'll try to fix this. I guess warnings would be fine--some code on the inside depends on those checks passing though.

**Comment by steph643** [comment]
Here is another use case (beyond debugging) for being able to pass no schema to a form block.

I have defined a generic form block for a boostrap modal:
```html
<template name="bootstrapModal">
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form>
                        ...
                        {{> UI.contentBlock data=data context=context}}
                        ...
                        <button type="submit" class="btn btn-primary" disabled="{{#if invalidCount}}disabled{{/if}}">Save</button>
                        ...
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</template>
```

I use this modal in various places in my app.

In one of those places, my form is a grid of checkboxes for setting group permissions (just like [this](http://codex.wordpress.org/Roles_and_Capabilities#Capability_vs._Role_Table)). This grid is generated dynamically (from two collections), so there can not be any associated schema.

Right now, in order to benefit from my modal form block, I am obliged to do this:

```html
	{{#bootstrapModal ... schema=th_schema ...}}
		...
	{{/bootstrapModal}}
```
```javascript
	th_schema: function()
		{
		// Returns empty schema
		return new SimpleSchema();
		}
```
It would be better if I could pass no schema at all. And there is no need for a warning either.

**Comment by jonjamz** [comment]
Thanks for the example, I'll look into this.

**Comment by jonjamz** [comment]
This should fix it. Please let me know if you still have issues.

**Comment by steph643** [comment]
Yup, works well!
