### ISSUE TITLE
Add support for nested objects (in schema or otherwise)

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#28]
Here is my code:
```html
<template name="myForm">
    {{#defaultFormBlock schema=schema action=action data=data}}
        {{> myInput field='field1'}}
        {{> myInput field='nested.field2'}}
        <button type="submit" disabled="{{#if context.invalidCount}}disabled{{/if}}">Submit</button>
    {{/defaultFormBlock}}
</template>
```

```javascript
schema: function ()
	{
	return new SimpleSchema(
		{
		field1: { type: String, max: 3 },
		nested: { type: Object },
		'nested.field2': { type: String, max: 3 }
		});
	},

data: function()
	{
	return { field1: '111', nested: { field2: '222' } };
	},
```

First issue is that `data` does not initialize `nested.field2`.

Second issue is that nested.field2 input is validated erratically: the latest error message seems to remain even if input is ok, until a new error is detected and replace the previous one.

**Comment by jonjamz** [comment]
This makes sense. I'll have to add this functionality.

**Comment by jktr** [comment]
I just ran into the same issue. May I ask, if you already have an estimate, by when this could be fixed?

**Comment by jonjamz** [comment]
I can probably do end of week on this. Thanks!

**Comment by jonjamz** [comment]
Made progress on this and will publish the changes once I finish more testing.

**Comment by jonjamz** [comment]
I tested this a bunch and it seems to be working. Please let me know how it goes for you. Thanks!

**Comment by steph643** [comment]
I will test this today.

**Comment by steph643** [comment]
It works like a charm, thanks a lot!

**Comment by jktr** [comment]
Just tested it - works flawless in my app. Thank you very much!
