### ISSUE TITLE
+1 for the comparison with Autoform

### ISSUE THREAD

**Issue by dandv** [meteortemplates/forms#3]
Thank you for including a [detailed comparison with the major prior art, Autoform](https://github.com/meteortemplates/forms#other-forms-packages). I'm surprised by the very large number of package authors who don't even mention existing packages, let alone the raison d'etre for them creating yet another one:

* https://github.com/morecoins/Donate-Button/issues/1
* https://github.com/hckrs/meteor-spin/issues/1
* https://github.com/1602/compound/issues/645
* https://github.com/keithamus/jwerty/issues/58
* https://github.com/dmauro/Keypress/issues/61
* https://github.com/awatson1978/clinical-ui-forms/issues/1
* https://github.com/yogiben/meteor-admin/issues/61
* https://github.com/SteelzZ/au-cmsinn/issues/2
* https://github.com/Strngs/comet/issues/12
* https://github.com/jelenajjo/meteor-page-transitions/issues/3
* https://github.com/TimSchlechter/bootstrap-tagsinput/issues/123
* https://github.com/maranomynet/linkify/issues/14
* https://github.com/Futurescaper/Futuregrapher/issues/6
* https://github.com/kaerus-component/urlparser/issues/2
* https://github.com/englue/meteor-publish-composite/issues/6
* https://github.com/voidberg/html5sortable/issues/57
* https://github.com/maxtaco/node-cryptojs/issues/2
* https://github.com/cassioscabral/meteor-sb-admin/issues/1
* https://github.com/ecohealthalliance/reactive-table/issues/10
* https://github.com/component/textarea-caret-position/issues/2
* https://github.com/jillix/a-csv/issues/4
* https://github.com/lifeswap/node-angellist/issues/1
* https://github.com/srveit/mechanize-js/issues/4
* https://github.com/chuangbo/meteor-cookie/issues/3
* https://github.com/lolos/jquery-Linker/issues/1
* https://github.com/CollegeDev/DonkeyGuard/issues/23
* https://github.com/fir3pho3nixx/grunt-spawn/issues/5

... and way more

**Comment by jonjamz** [comment]
Not a problem!

I went into even more detail about why I created the package [here].(https://groups.google.com/d/msg/meteor-talk/k3nAeQTOjYU/F-ZLzyPQon0J)
