### ISSUE TITLE
Wow, did you know you can do nested elements?

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#31]
```html

<template name="bootstrapLabel">
    <label class="control-label">
        {{#if schema.label}}{{schema.label}}{{else}}{{field}}{{/if}}
    </label>
</template>

<template name="bootstrapErrorMsg">
    <p class="help-block">{{#if valid}}{{instructions}}{{else}}{{errorMessage}}{{/if}}</p>
</template>

<template name="bootstrapInput">
    <div class="form-group  {{#unless valid}}has-error{{/unless}}">
        {{> bootstrapLabel}}
        <input name="{{field}}" class="form-control reactive-element" value="{{value}}">
        {{> bootstrapErrorMsg}}
    </div>
</template>

<template name="bootstrapTextarea">
    <div class="form-group  {{#unless valid}}has-error{{/unless}}">
        {{> bootstrapLabel}}
        <textarea name="{{field}}" class="form-control reactive-element">{{value}}</textarea>
        {{> bootstrapErrorMsg}}
    </div>
</template>
```
You need to call `createElement` on each one in order to benefit from helpers.

Worth mentioning in the doc?

**Comment by jonjamz** [comment]
I actually did not know that, but I was planning on investigating this type of functionality. Cool to see that it's already there.

It makes sense--as long as you don't have any HTML elements with `class='reactive-element'`, it won't run validation.

**Comment by jonjamz** [comment]
I was also able to make this work, and I've started to wrap all my elements with it, leaving just the basic element code in the main element templates. It's a lot nicer!

```handlebars
<template name="elementContainer">
  <div class="elementContainer-container">
    <label>{{label}}</label>
    <br>

    {{> UI.contentBlock field=field}}

    {{#if submitted}}
      {{#if errorMessage}}<p class="error-message">{{errorMessage}}</p>{{/if}}
    {{/if}}
  </div>
</template>
```

**Comment by jonjamz** [comment]
Added a section about this in the docs, right after the section on element template helpers.

**Comment by jonjamz** [comment]
https://github.com/meteortemplates/forms#using-nested-elements-for-cleaner-code

**Comment by jonjamz** [comment]
(cut from a different issue)--

Possibly unrelated, but when I was testing the package last night, I noticed that you can do this:

```handlebars

<template name="testForm">

  {{#basicFormBlock schema=schema action=action}}
    {{> basicInput field='testField'}}
    
    <!-- Anything in testForm's context can be used here with no extra work -->
    {{someDataFromTestForm}}
  {{/basicFormBlock}}

</template>

```

**Comment by steph643** [comment]
I have some remarks about your [new chapter](https://github.com/meteortemplates/forms#using-nested-elements-for-cleaner-code):

-1-

```html
<template name="bootstrapLabel">
  <label class="control-label">
    {{#if label}}
      {{label}}
    {{else}}
      {{field}}
    {{/if}}
  </label>
</template>
```
I think {{label}} always returns something, so testing it with {{#if}} is meaningless. Here is what makes sense:
```html
<template name="bootstrapLabel">
  <label class="control-label">
    {{#if schema.label}}
      {{schema.label}}
    {{else}}
      {{field}}
    {{/if}}
  </label>
</template>
```

-2- 

You use a class `myElementContainer-container` which I think is useless. Isn't it?

-3-

For the clarity of the example, I think you should avoid defining a form block and use defaultFormBlock instead.

-4-

I think there is a typo: you use `components__elementContainer` instead of `myElementContainer ` (3 times)

-5-

I don't think I would choose the same architecture as you:
```html
<!-- Block helper to wrap any Elements -->
<template name="myElementContainer">
  <div class="myElementContainer-container">
    <label>{{label}}</label>
    <br>
    <!-- Make sure to pass `field` -->
    {{> UI.contentBlock field=field}}
    <!-- Show error if submitted but not successful -->
    {{#if submitted}}
      {{#if errorMessage}}<p class="error-message">{{errorMessage}}</p>{{/if}}
    {{/if}}
  </div>
</template>

<!-- Element template -->
<template name="myInputElement">
  <input placeholder={{schema.instructions}} class="reactive-element" value={{value}}>
</template>

<!-- Here's a form using all the above components -->
<template name="myLeadGenForm">
  {{#myFormBlock action=action schema=schema data=data}}

    {{#myElementContainer field='firstName'}}
      {{> myInputElement}}
    {{/components__elementContainer}}

  {{/myFormBlock}}
</template>
```

I would rather use (not tested):

```html
<!-- Block helper to wrap any Elements -->
<template name="myElementContainer">
  <div class="myElementContainer-container">
    <label>{{label}}</label>
    <br>
    <!-- Make sure to pass `field` -->
    {{> UI.contentBlock field=field}}
    <!-- Show error if submitted but not successful -->
    {{#if submitted}}
      {{#if errorMessage}}<p class="error-message">{{errorMessage}}</p>{{/if}}
    {{/if}}
  </div>
</template>

<!-- Element template -->
<template name="myInputElement">
    {{#myElementContainer field='firstName'}}
      <input placeholder={{schema.instructions}} class="reactive-element" value={{value}}>
    {{/myElementContainer }}
</template>

<!-- Here's a form using all the above components -->
<template name="myLeadGenForm">
  {{#myFormBlock action=action schema=schema data=data}}
      {{> myInputElement}}
  {{/myFormBlock}}
</template>
```

**Comment by jonjamz** [comment]
Thanks for finding that typo!

I chose to wrap elements in the form instead of inside the element templates because it allows me to create any arbitrary wrapper (for example, one that shows error messages after submit, or one that shows error messages before) and still use the same elements across different ones. That way I can add any extra helpers to the elements and I won't have to rewrite those based on how I want to format the other states.

As for the container, it just helps to stack my fields properly in the form without using too much other markup. Maybe it's distracting in the example.

**Comment by jonjamz** [comment]
Should be better now.

**Comment by steph643** [comment]
You are still using a `element-container` class. Is it useful? (risk of confusion with the mandatory `reactive-element` class).

**Comment by steph643** [comment]
Another typo in your [new chapter](https://github.com/meteortemplates/forms#using-nested-elements-for-cleaner-code):

"Create a partial Element template, but without the usual **.reactive-class**"

Should be **.reactive-element**, right?

**Comment by steph643** [comment]
Another error in your [new chapter](https://github.com/meteortemplates/forms#using-nested-elements-for-cleaner-code):

See my **EDITED** comment at the top of this thread: you have to replace `{{#if valid}}` by `{{#if ../valid}}`.

(why?)

**Comment by jonjamz** [comment]
Ah interesting. Ok I'll fix that, and I'll have to look into what's going on with `valid`.

**Comment by jonjamz** [comment]
Ok, I think I figured this out.

In order for an element to have a `valid` state, it has to itself be taking an input and validating it.

The reason you have to use `{{../valid}}` is because you're actually accessing the parent template (element) state.

This brings up another point, which is--you probably don't need to run your nested elements through `ReactiveForms.createElements`. Instead, you might just need to use the dot notation to go up one level and get the parent element's state.

```handlebars
<template name="bootstrapLabel">
    <label class="control-label">
        {{#if ../schema.label}}{{../schema.label}}{{else}}{{../field}}{{/if}}
    </label>
</template>
```

This is probably a more efficient way to do it as well--so it should probably be what's recommended in the docs.

**Comment by steph643** [comment]
What you suggest doesn't seem to work.

When I use `ReactiveForms.createElement()`:
* `{{schema}}` is ok
* `{{../schema}}` returns `undefined`

When I don't use `ReactiveForms.createElement()`:
* `{{schema}}` returns `undefined`
* `{{../schema}}` returns `undefined`

**Comment by jonjamz** [comment]
You're right, I wasn't able to get this to work in testing either.

The helpers don't seem to be accessible using `../` or even `Template.dynamic`.

**Comment by jonjamz** [comment]
Looks like I've solved this locally, and will be releasing an update after more testing.

**Comment by jonjamz** [comment]
@steph643 you shouldn't need to use `../valid` anymore, but I haven't tested that personally yet. All the elements with the same `field` now share the same reactive data context when inside a form block.

**Comment by steph643** [comment]
This doesn't work for me: `{{valid}}` is defined but not reactive.

Notice that:
- `{{../valid}}` still works correctly.
- `{{errorMessage}}` is defined and reactive.

**Comment by jonjamz** [comment]
Ah--I see why that is now. I've been using the block helper format to great success, though.

I'll try to get the elements to recognize when they're inside another element!

**Comment by jonjamz** [comment]
The next version has support for one level of nested elements.

**Comment by steph643** [comment]
It seems some things have been broken lately. Here is the current behavior when using a nested component:

**Case the nested component has not been registered with createElement**:
* {{field}}: correct value
* {{value}}: undefined
* {{valid}}: undefined
* {{schema}}: undefined
* {{errorMessage}}: undefined
* {{instructions}}: undefined
* {{../*anything*}}: undefined

**Case the nested component has been registered with createElement**:
* {{field}}: correct value
* {{value}}: null
* {{valid}}: correct value but non reactive
* {{schema}}: undefined
* {{errorMessage}}: undefined
* {{instructions}}: undefined
* {{../*anything*}}: undefined

With the previous version, I could access {{schema}} in a sub-template registered with createElement. With older versions, I am quite sure I could access {{errorMessage}} or {{../errorMessage}}.

I think this is not an essential feature. Unless I am wrong, you can always pass what you need as a sub-template parameter. However, what we miss in the doc is a simple and consistent rule, such as 'always use ../ to access helpers from a sub-template' or 'in order to use helpers from a sub-template, pass the values as template parameter').

**Comment by jonjamz** [comment]
I think you should be able to access all those things in the latest version. I just looked through the code again and I'm not seeing any red flags. If you could create a test repo with the components you're trying to use, it would make it easy for me to diagnose the problems you're facing.

Are you using the current stable release of Meteor, or are you using the `devel` branch? I know they're changing the way some of the Template methods work in the next update, and that might affect this package.

Here is an example of a nested element that works for me. This element is made up of two other sub-elements that are registered as self-contained elements in their own right:

*Handlebars*
```handlebars

<!-- Multi-select that gets options based on a query and saves the selections -->

<template name="components__collectionPickerElement">

  {{!-- Select an item to affect the other list --}}
  {{!-- The `standalone=true` stops this element from syncing data with parent context --}}
  <section class="selector-container">
    {{> components__selectElement
      items=selectData
      valueKey=selectValueKey
      nameKey=selectNameKey
      standalone=true
    }}
  </section>

  {{!-- Here's the list of related items --}}
  <section class="checkList-container">
    {{!-- Hide the no items message if no select value has been chosen --}}
    {{!-- Pass through value --}}
    {{> components__checkListElement
      items=checkListItems
      disabledItems=value
      selectedItems=value
      showMessage=selectValue
      message=checkListMessage
    }}
  </section>

</template>
```

*Coffeescript*
```coffeescript
ReactiveForms.createElement
  template: 'components__collectionPickerElement'
  passThroughData: true
  validationEvent: 'change'
  validationSelector: '.checkList-container .reactive-element'
  validationValue: (el, clean, template) ->
    $el = ($ el)

    # Stop from initially validating if no checklist is present.
    unless !!$el.find('li').length
      return this.stop

    else
      values = $el.find(':checked').not(':disabled').map ->
        return this.getAttribute('data-id')

      return _.reject values, (item) ->
        return Match.test(item, Function)

  created: ->
    this.selectValue = new ReactiveVar()
```

There is some other code as well with custom helpers and event handlers, but it's minimal.

Then I use the nested element in the form like this (nested again inside a wrapper element):

*Handlebars*
```handlebars
{{#components__elementContainer
  field='additionalItems'
  title='These tags will be added to:'
}}
  {{> components__checkListElement
    field='additionalItems'
    items=items
    disabledItems=currentItem
    selectedItems=currentItem
    showMessage=true
    message='No items found!'
  }}
{{/components__elementContainer}}
```

Here is the code for the wrapper element:

*Handlebars*

```handlebars
<template name="components__elementContainer">
  <div class="components__elementContainer-container">
    <label class="components__elementContainer-label {{field}}">
      {{#if title}}
        {{title}}
      {{else}}
        {{label}}
      {{/if}}
      {{#if errorMessage}}
        <em><small>{{errorMessage}}!</small></em>
      {{/if}}
    </label>
    <br>

    {{> UI.contentBlock}}

    {{!-- Pass `notifications=true` to view these --}}
    {{#if notifications}}
      <br>
      {{#if remoteValueChange}}
        <em>
          <small>
            The underlying data for {{label}} has changed.
            <span class="preview-changes" title={{newRemoteValue}}>Hold cursor here to view.</span>
            <button class="accept-changes">Accept</button>
            <button class="ignore-changes">Ignore</button>
          </small>
        </em>
      {{/if}}
    {{/if}}
    <div style="clear:both"></div>
  </div>
</template>
```

The key to getting all the data to pass-through in the wrapper was not to specify any custom data in `{{> UI.contentBlock}}`. Before, I was using `{{> UI.contentBlock field=field}}` but that actually created a new data context for the wrapped component. 

The wrapper element is registered like this:

*Coffeescript*

```coffeescript
Template['components__elementContainer'].events

  'click .accept-changes': (e, t) ->
    e.preventDefault()
    inst = Template.instance()
    component = inst[ReactiveForms.namespace].acceptValueChange()

  'click .ignore-changes': (e, t) ->
    e.preventDefault()
    inst = Template.instance()
    component = inst[ReactiveForms.namespace].ignoreValueChange()

ReactiveForms.createElement
  template: 'components__elementContainer'
```

This all works really well for me as nested reusable form components. In one app, I'm using this nested component in 3 different forms.

**Comment by steph643** [comment]
Thanks for the long answer.
I had never tried to use UI.content block without the usual arguments (data & context). Trying this quickly, I get the following exception:
```
Uncaught TypeError: Cannot convert undefined or null to object            underscore.js:1072 
_.has                                  underscore.js:1072
ReactiveForms.elements.createdFactory                module.coffee:395
```
I need to go deeper in your example. I will have a look tomorrow.
