### ISSUE TITLE
Provide `_id` in form data context for action function

### ISSUE THREAD

**Issue by jonjamz** [meteortemplates/forms#38]
Right now, when you pass initial data from a document into a form block, the `action` function only shows fields without the document's `_id`. This makes it difficult to update doc.

If the `_id` field is provided in initial data (and it's likely a document) it should pass through to the form data context and exist as `this._id` in the `action` function.

**Comment by steph643** [comment]
Great!

**Comment by alexofob** [comment]
Hi, 
In the latest version of this package, _id is not provided in the data context of the action function. Kindly fix this. 
I tested the functionality successfully on 1.13.3 but on upgrade to 1.14, _id was not passed.

Thanks.

**Comment by jonjamz** [comment]
Thank you for reporting this serious issue. I will fix this.

**Comment by steph643** [comment]
Just been hit by this also.

**Comment by jonjamz** [comment]
I fixed this and it'll be in the next release.
