### ISSUE TITLE
custom validation not working with meteortemplates:forms

### ISSUE THREAD

**Issue by gussandy** [meteortemplates/forms#4]
Hey Jon, 
Nice piece of work...thanks...Jon, I'm having a bit of trouble getting SimpleSchema custom validation working with forms...my app simply crashes however, when I use the same piece of code in another project I'm working on all is well. Is there something I need to know when writing SimpleSchema custom validation with forms? A heads up on this would be great.

**Comment by jonjamz** [comment]
I believe I have found the source of this bug. Will push an update as soon as I verify.

**Comment by jonjamz** [comment]
Tested locally using the following schema (taken from the SimpleSchema tests):

```coffeescript
confirmSchema = new SimpleSchema
  password:
    type: String
    instructions: "Enter a password!"
    custom: ->
      console.log("this", this)
  confirmPassword:
    type: String
    custom: ->
      console.log("this", this)
      console.log("this.field('password')", this.field('password'))
      if this.value isnt this.field('password').value
        return "passwordMismatch"
    instructions: "Confirm your password!"
```

Using this schema, my app wasn't crashing before the update--but I noticed `this.field` was undefined. After the update, everything works for me.

Form elements are now validated using the surrounding form block's data context where available, which means you should be able to use all the properties and methods on `this` as usual in your custom validation.

**Comment by jonjamz** [comment]
There is one caveat--`this.field()` will only have access to values that have passed validation.

I'm assuming this is the best way to go. If you think it's better to allow invalid values at this step, I'm open to discussing it in a separate issue.

**Comment by gussandy** [comment]
Thanks Jon...will give it a go later...

**Comment by gussandy** [comment]
Hey Jon...Thanks for your help, everything seems to be working fine.

**Comment by jonjamz** [comment]
Thanks for letting me know. I'm here if you have any other questions or concerns. :+1:

**Comment by zimt28** [comment]
Doesn't work for me ..

```coffee
password:
  type: String
confirmPassword:
  type: String
  custom: ->
    console.log @field('password').value
    if @value isnt @field('password').value
      return 'passwordMismatch'
```

So whenever I use the `confirmPassword` field, I don't get the value of `password` logged but `undefined`.

**Comment by danielparas** [comment]
Hi, I'm having trouble getthing `this.field()` to work. @jonjamz, I replaced my code with the code you pasted in your comment on Jan 12 and the result is as follows:

```
this 
Object {key: "confirmPassword", genericKey: "confirmPassword", definition: Object, isSet: true, value: "thisisatest"…} 
password 
Object {isSet: false, value: undefined, operator: undefined}
```

As you can see the returned values for this.field are all unset/undefined. Any ideas what could be wrong?

FYI
aldeed:simple-schema            1.3.3
templates:forms                 1.14.2
