### ISSUE TITLE
How to re-initialize (clear) form after successful submit?

### ISSUE THREAD

**Issue by satyavh** [meteortemplates/forms#51]
After successful submit, {{success}} is set, but as I understand the form is only initialized to its empty state again when the user changes something in the form, resulting in {{changed}} set. But usually in forms, after a successful submit the form is cleared. 

One option is:

```
$('.reactive-element').val('')
```

But that only clears the formfields and not the helpers like {{valid}} and {{success}
So how to manually clear the form-state from javascript?

**Comment by jonjamz** [comment]
I've been manually clearing elements in the action function. But I think I can do better.

I should release a *reset* feature like this:

```javascript
ReactiveForms.createElement({
  template: 'checkBoxElement',
  validationEvent: 'change',
  validationValue: function (el, clean, template) {
    return $(el).is(':checked');
  },
  reset: function (el, template) {
    $(el).removeAttr('checked');
  } 
});
```

Then you could call that function on all elements automatically in the action function, like this:

```javascript
callbacks.reset();
```

Calling that would also clear all data in the form's data context.

Sound good?

**Comment by satyavh** [comment]
I think you need to auto-reset/clear the form after success. It's the normal pattern for forms.

Also I've been diving in the code a little and did a quite some experiments, but clearing values / attributes doesn't seem to do the complete trick. Because the elements remember (save) their value and their valid state - even if you reset the value manually via jquery.

The 'problem' is the architecture - as far as I understand. 
The elements are looking at to the form block state and save their values in the form block. So even if you clear the element using jquery, they still think they are valid, or that their status is 'changed'.

Also I couldn't find a way for the form block to set/reset the state of the individual elements. Communication seems to be one-way only.

**Comment by jonjamz** [comment]
The architecture is not the problem. It will be trivial to add in resetting functionality, it's just not in there yet. 

It would be too presumptive to auto clear a form after success. That's not something provided by HTML forms by default, for a reason.

**Comment by satyavh** [comment]
I feel it's better that it clears by default, and that you can customize this with the reset option - for more power. But it's your package :-)

Perhaps you can share with me how you reset the form now? Because just using jquery to empty the fields doesn't do the trick for me, it keeps the valid state per element.

**Comment by jonjamz** [comment]
My main concern is that for all the forms I've built, I'm doubling them as insert and update forms. So in the action function, I check `if (changed)

**Comment by satyavh** [comment]
No just that fills the form with ''

Some more feedback: I got this form (it's in jade)
```
template(name="passwordField")
  .form-groupdiv(class="{{#unless success}}{{#if valid}}has-success{{/if}}{{/unless}}")

    p s: {{submitted}} sc: {{success}} ch: {{changed}} va: {{valid}}
    p {{..success}}{{../success}}
    label.control-label
      {{schema.label}}
    input.form-control.reactive-element(type="password", name="{{field}}", placeholder="{{schema.instructions}}")
    unless success
      if valid
        i.fa.fa-check-circle
    p.help-block
      if ../valid
        | {{instructions}}
      else
        | {{errorMessage}}
```

so what happens when you place 3 of these forms in a form block, and clear the forms in the action with:
```
$('.reactive-element').val('')
```
First the form fields are successfully cleared and the `has-success` class is correctly removed.
But here is the issue. Once you start typing in the first form field, the `has-success` class is reapplied to all field.

This bug also occurs with your solution.

**Comment by jonjamz** [comment]
See https://github.com/meteortemplates/forms/blob/master/lib/module.coffee#L126-L130.

When you change a form you've already submitted, the `success` state is removed and the `changed` state is `true`.

What schema are you using? Does it allow for blank form field values?

Please show me your schema and any `validationValue` functions on your elements.

**Comment by satyavh** [comment]
Yes that's what I understood. But it seems it's only removed from the form block, not the elements.
So the elements keep their valid en success state - something like that

```
Template['changePasswordForm'].helpers
  schema: ->
    new SimpleSchema(
      currentPassword:
        type: String
        min: 4
        instructions: 'Current password'
        label: 'Current password'
      newPassword:
        type: String
        min: 4
        label: 'New password'        
      confirmPassword:
        type: String
        min: 4
        label: 'Confirm new password'   
        custom: ->
          if @value != @field('newPassword').value 
            return "passwordMismatch"
          true

    )
  action: ->
    (els, callbacks, changed) ->
      Accounts.changePassword(@currentPassword, @newPassword, (error) ->
        unless error
          $('.reactive-element').val('')
          callbacks.success()
        else
          callbacks.failed()
      )
```

Template

```
template(name="changePasswordForm")
  +formBlock(schema=schema action=action)
    +passwordField(field="currentPassword")
    +passwordField(field="newPassword")
    +passwordField(field="confirmPassword")
```

formBlock
```
template(name="formBlock")
  form
    +UI.contentBlock data=data context=context
    p
      button.btn.btn-default(type="submit" disabled='{{#if isNull invalidCount success}}disabled{{/if}}') Submit
      span
        if loading
          | Loading...
        if invalid
          | Can't submit! There are {{invalidCount}} invalid fields!
        if failed
          | There was a problem submitting the form!
        if success
          | Success! Form submitted (to nowhere)
```

**Comment by jonjamz** [comment]
This looks pretty normal to me. I'll investigate this resetting issue today and publish an update.

Sorry that this has been such a headache!

**Comment by satyavh** [comment]
Cool appreciate that. I'll wait for your fix. Apart from this, this package is really awesome,has lots of potential.

**Comment by satyavh** [comment]
hi, how is it going with this? Do you think you'll have a fix out after the weekend? Otherwise I need to start using something else, which sucks :-)

**Comment by jonjamz** [comment]
Will work more on it today. Hoping it won't be too much longer. Unfortunately I have to put my full-time job first, and it's been a crazy week!

**Comment by satyavh** [comment]
If you can't get it done these days I totally understand. It's really awesome you made this in your own time. I'll try to wait for your fixes but at some point I'll have to use something else to move forward.

**Comment by jonjamz** [comment]
Just an update--I've made pretty good progress on this and a few other issues and should be fine publishing a new version this weekend. Thanks for being patient.

**Comment by jonjamz** [comment]
This should be fixed. I tested it in several forms and it works for me.

You need to specify a custom `reset` method as shown in the docs here:

https://github.com/meteortemplates/forms#3-register-the-reactiveforms-components-if-needed

Then, use `callbacks.reset()` in your action function to run the reset on all the elements in the form. This will also reset the form's reactive states and clear the form's data context.

https://github.com/meteortemplates/forms#1-provide-a-schema-and-an-action-function

Hope this works for you. Please let me know of any quirks and I'll be sure to jump in and fix them quickly.

**Comment by satyavh** [comment]
Cool thanks! 
I've tested it and fields are indeed successfully cleared according to the reset function. Thumbs up!

However, unfortunately {{success}}, {{changed}}, {{submitted}} and {{valid}} are all not reset - meaning, the form is not reset to its initial state.

I'm still using the same form template as before - nothing changed.

I tried to do something like this:

```
ReactiveForms.createElement
  template: 'passwordField'
  validationEvent: 'keyup'  
  reset: (el) ->
    $(el).val(null)
    @valid.set(false)
    @success.set(false)
```

and that clears the valid and success state, but also results in errors. Plus, I got 3x the same form in the form block, and when I start typing in the first one, the other 2 are set to valid again. So that doesn't work.

**Comment by jonjamz** [comment]
If there's any way you could create a repo that I could use for testing (with your setup) I think I could help solve your issues quickly. 

On reset, I do set those states to false (init state) so I'm thinking there must be some unique case maybe with how you're using the package that I should understand better.

**Comment by satyavh** [comment]
Hi, I've setup a repro here: https://github.com/satyavh/form-test
Once you got it, make sure to create an account, because with the form you can change your password.
Hope you can figure out what I'm doing wrong / what goes wrong.

**Comment by jonjamz** [comment]
Thank you so much! I will jump right in.

**Comment by satyavh** [comment]
Hi, did you find the time to have a look? Any new insights?

**Comment by jonjamz** [comment]
I've been doing some more extensive testing with the latest version, and found a few issues. I'm reorganizing some of the code today to get around those, and in the process I'll run your repo against the latest version and see how it goes.

**Comment by jonjamz** [comment]
I got everything to work normally with the latest release. You were right, it wasn't resetting all the states.

There are two types of resets now. The default won't reset the `success` or `failed` states or their custom messages (although these are automatically cleared the next time the form is changed). If you want to simply reset everything, pass `true` into the callback, like `callbacks.reset(true);`.

**Comment by satyavh** [comment]
awesome!! Works like a charm. Nice job, thanks!

**Comment by satyavh** [comment]
actually, for me {{valid}} helper for element doesn't get cleared. 
Does this reset for you?

**Comment by jonjamz** [comment]
I'll have to double-check later today. I may have forgotten to clear the schema context in the reset.

Thanks for sticking with the package as I iron these things out!
