### ISSUE TITLE
Add support for an array of events in `validationEvent`

### ISSUE THREAD

**Issue by krevativ** [meteortemplates/forms#52]
You can define "keyup" or "change" event for an element (this also need to be documented somewhere). For a number field for example I need both events. Because the arrows of the number field triggers only the change event. Is it possible to define both events at the same time?

**Comment by jonjamz** [comment]
Yes, although this is something I can handle more gracefully in `v2.0.0`. You'd do this:

```javascript
validationEvent: 'change .reactive-element, keyup`
```

See https://github.com/meteortemplates/forms/blob/master/lib/module.coffee#L718.

**Comment by krevativ** [comment]
Great! Thank you :)

**Comment by jonjamz** [comment]
This is supported in the latest release `1.13.1`:

`validationEvent: ['change', 'keyup']`
