### ISSUE TITLE
How to manually invalidate a field?

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#53]
Here is my use case:

I have this field, where the user has to input the url of an image:
```javascript
	pictureUrl:
		{
		label: 'Picture URL',
		type: String,
		regEx: SimpleSchema.RegEx.Url,
		max: 500
		}
```
While the user is typing, in the background, I load the image to see if it of the right dimension (get the result asynchronously). If the result is not good, I would like to manually insert a custom error message in the 'pictureUrl' field.

I tried the following, but it doesn't update the display accordingly:
```javascript
	var schemaContext = Template.currentData().context.schemaContext;
	schemaContext.addInvalidKeys([{name: 'picture', type: 'notAllowed' }])
```

**Comment by steph643** [comment]
Linked to https://github.com/meteortemplates/forms/issues/51?

**Comment by steph643** [comment]
One remark: calling `schemaContext.addInvalidKeys()` does not update `{{valid}}` at the element level, but updates `{{invalidCount}}` at the block level.

**Comment by jonjamz** [comment]
Interesting. I'll have to build in a way to connect the `{{valid}}` deps to Simple Schema. Shouldn't be too hard.

**Comment by jonjamz** [comment]
This should be fixed. Please test and let me know. Thanks!

**Comment by steph643** [comment]
It works well, except for the fact that it seems `{{valid}}` now returns false when the form is valid and true when it is not :-)

**Comment by jonjamz** [comment]
Woops! Should be fixed.

**Comment by steph643** [comment]
Works well, thanks!
