### ISSUE TITLE
Standalone Form Elements trigger 'Uncaught TypeError'

### ISSUE THREAD

**Issue by jktr** [meteortemplates/forms#54]
Form Elements that are used standalone, i.e. not in a Form Block, trigger an error in the browser:

>Uncaught TypeError: Cannot convert undefined or null to object

This behavior can be reproduced with the following code (basically taken from the documentation):

myFormTemplate.html:

    <template name="myFormTemplate">
      <p>The form.</p>
      {{> basicInput schema=schema field='testField'}}
    </template>

myFormTemplate.js

    ReactiveForms.createElement({
      template: 'basicInput',
      validationEvent: 'keyup'
    });
    
    
    Template.myFormTemplate.helpers({
      schema: function () {
        return new SimpleSchema({
          testField: {
            type: String,
            max: 3,
            instructions: "Enter a value!"
          }
        });
      },
      action: function () {
        return function (els, callbacks, changed) {
          console.log("[forms] Action running!");
          console.log("[forms] Form data!", this);
          console.log("[forms] HTML elements with `.reactive-element` class!", els);
          console.log("[forms] Callbacks!", callbacks);
          console.log("[forms] Changed fields!", changed);
          callbacks.success(); // Display success message.
          callbacks.reset();   // Run each Element's custom `reset` function to clear the form.
        };
      }
    });

**Comment by jonjamz** [comment]
Should be fixed in latest release. Please let know if you have any other problems. Thanks.
