### ISSUE TITLE
Distinguish better between two types of `changed` states in API

### ISSUE THREAD

**Issue by mcrayne** [meteortemplates/forms#56]
Continuing discussion from #46.

<deleted>The changed state initializes as false.<deleted>
**It becomes true on the first user-enacted change in the form.** 
The following events do not affect changed state:

Data from the schema being used to set up fields--for example, allowedValues used in a select field.
**Initial data passed into the form block.**
Remote updates to (reactive) initial data.

My question - when there exists initial data passed into the form block, should the "changed" state be set upon any change to the data before blurring or only after blurring? For example - in your example you suggest pressing the back key. Great! the Changed state is set to true. BUT if I re-enter the same value (i.e. the value has not changed from its' original value now) shouldn't the Changed state be set to false?

Or, am I missing an option? Can I set the "changed" state on blur instead of keyup?
Or, should I ask this question in the aldeed:simple-schema project?

Thanks for some really great work!

**Comment by jonjamz** [comment]
Thanks for using the package!

The way it is now, I think you'd just have to set the `validationEvent` to `blur` instead of `keyup`. Although then the user wouldn't have validation feedback on `keyup`.

The `changed` state kicks in when data from user input passes validation and hits the internal form data context. So it's not really a Simple Schema issue. 

I'm working on adding a hook into the package that'll be released this weekend, and I think that might be a good place to allow you to manually set `changed` if you want. But then you'd need a way to disable the default functionality, and that might be part of a different update.

See here:
https://github.com/meteortemplates/forms/issues/55

**Comment by mcrayne** [comment]
Wow! Thanks for getting back to me! I was just re-reading your docs and this is the behaviour you want to see 
>If a field was changed to a different value and back, it will still be in this object.

The use case I am dealing with is this - I don't do updates to existing data - for regulatory audit trail reasons.. I always create a new version of the form data with a pointer to the previous version. I keep track separately of what is the current version.  (Though, by definition, it is a version of the form that no other version is pointing to, but that is kludgy run every time I need to load the current version - which is virtually every time). I know at first glance that seems wasteful but in actual practice the data doesn't change that often and it is the most secure way I have of preventing unauthorized changes to existing data by making the mongoDB collections insert only.

Anyways - if a user opens a form and changes then reverts their changes, they literally have not altered the form. In that case, I alert them and then don't save the form. Otherwise, I can end up with an endless series of data versions that have not really changed, just have a new createdBy and createdAt values. 

If I change the validationEvent to blur it would set the changed flag if the field actually changed, but if the user then returns focus to the field and changes the value back to the original state, I am back where I started because the changed flag will still be set to true - if I understand this properly.  

Very nice code BTW - I learned a lot from it.

**Comment by jonjamz** [comment]
I think there are two ways to use the `changed` state. 

One is to say "the user made a change to the form in the UI." For example, you might want to start a form collapsed and then reveal the submit button when the user types something in. In that case, it's useful to have the `changed` state the way I have it now.

The other (your use case) is to say "the data is different than it was before." 

Of course both of these are totally legitimate ways to use `changed` and I think the interpretation could even be different across two forms in the same app.

The question now is, do I make it a toggle, or do I offer both in different helpers? 

And at the action function, I'd bet that nobody wants to see things in the `changed` argument that haven't actually changed, regardless of user input.

**Comment by jonjamz** [comment]
Latest update should take care of this. Please see the changelog.
