### ISSUE TITLE
Not sure about {{invalid}} documentation

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#6]
>{{invalid}}
>This is true if any ReactiveForms element in the form block is invalid.

This does not seem to be quite true. From what I have tried, it seems {{invalid}} shows an error only after pressing submit. To see "if any ReactiveForms element in the form block is invalid", I use {{invalidCount}} which works as described.

**Comment by jonjamz** [comment]
You're right about this. 

https://github.com/meteortemplates/forms/blob/master/templates:forms.coffee#L132

That is the only place `setInvalid()` is called--after the first submission. Once all the form fields become valid, though, `{{invalid}}` is set to `false` again until the next submission.

Meanwhile, `{{invalidCount}}` works all the time. 

I can change `{{invalid}}` to reflect the state at all times, and people can just run `{{#if submitted}}` around it. Do you have any preference or thoughts about whether this is the best course of action?

Thanks for pointing this out.

**Comment by jonjamz** [comment]
I'm going to close this since I've addressed it, but let's continue the dialog.

**Comment by steph643** [comment]
Thanks for your answer.
I have no experience in complex form workflows, so I don't have much of an opinion about that.
As long as the doc is accurate, I am happy :-)
