### ISSUE TITLE
Be clearer about what the framework API is for newcomers

### ISSUE THREAD

**Issue by keithn** [meteortemplates/forms#60]
Just thought I'd share my initial impression, I'm going to spend more time digging into exactly what the package is doing ( mainly because there aren't too many options to consider ), but I thought it might be useful to get a "never seen it before" impression of the docs.

I just found mention of this package on the forums when looking for an alternative to autoforms, so I came here and read the documentation.

I was totally lost almost straight away.  It felt like it was trying to introduce simple concepts, then rushed off on tangents without introducing all the concepts or making it clear what *is* the framework parts.  The code example seems way too big and NOT simple at all.  There's a lot of code to work through and its not clear where the framework is being leveraged and how it all hooks together.

I think you need the most MINIMAL and complete example without any other packages.

Then introduce something more complex that shows a lot more of the advantages.

Make it clear what the framework API is.

Ok, that's my first impression,  going to go back, and figure it all out now :-)

**Comment by keithn** [comment]
I tried to make the simplest possible working thing, started a new meteor app

autopublish      1.0.3  Publish the entire database to all clients
insecure         1.0.3  Allow all database writes by default
meteor-platform  1.2.2  Include a standard set of Meteor packages in your app
templates:forms  1.14.0  Dead easy reactive forms with validation.

html 

<head>
  <title>hello</title>
</head>

<body>
  {{> myForm}}
</body>

<template name="myForm">
  {{#basicFormBlock schema=schema action=action}}
    {{> basicInput field='name'}}
  {{/basicFormBlock}}
</template>

coffee

Template.myForm.helpers
  schema: ->
    new SimpleSchema
      name:
        type: String
        instructions: "Enter your name"
  action: ->
    (els, callbacks, changed) -> console.log "Action"

while I get a form on the screen, theres no placeholder, and the console doesn't show anything on submit.

**Comment by jonjamz** [comment]
Thank you for your feedback. I've been working on a docs rewrite, and it should be up very soon. There are several other issues relating to docs improvements, for example Issue #14 (which says this improvement is long overdue). I hope to close all of them this weekend.

Until then, please don't hesitate to ask questions in this issue. I will do my best to answer quickly.

**Comment by keithn** [comment]
I tried to get the "simplest" thing working, and am having trouble

```html
<head>
  <title>hello</title>
</head>

<body>
  {{> testForm}}
</body>
  
<template name="testForm">
  {{#basicFormBlock schema=schema action=action}}
    {{> basicInput field='testField'}}
  {{/basicFormBlock}}
</template>
```
and 

```javascript
Template['testForm'].helpers({
  schema: function () {
    console.log("create schema");
    return new SimpleSchema({
      testField: {
        type: String,
        max: 3,
        instructions: "Enter a value!"
      }
    });
  },
  action: function () {
    console.log("create action")
    return function (els, callbacks, changed) {
      console.log("[forms] Action running!");
      console.log("[forms] Form data!", this);
      console.log("[forms] HTML elements with `.reactive-element` class!", els);
      console.log("[forms] Callbacks!", callbacks);
      console.log("[forms] Changed fields!", changed);
      callbacks.success(); // Display success message.
      callbacks.reset();   // Run each Element's custom `reset` function to clear the form.
    };
  }
});
```

I get a form with a field on the screen, but no placeholder text, and nothing happens on submit.

**Comment by jonjamz** [comment]
I think the reason this isn't working for you is that you didn't follow step 3 of the usage guide?

**Comment by keithn** [comment]
up and running :)

**Comment by barisro** [comment]
<body>
  {{> testForm}}
</body>

<template name="testForm">
  {{#basicFormBlock schema=schema action=action}}
    {{> basicInput field='testField'}}
  {{/basicFormBlock}}
</template>

Where do I set the data ?
