### ISSUE TITLE
form context in UI.contentBlock

### ISSUE THREAD

**Issue by gibson** [meteortemplates/forms#64]
I create own form 
```
<template name="smartForm">
    <form class="{{class}}">
	    {{> UI.contentBlock data=data context=context}}
    </form>
</template>
```
and form has content 
```
{#smartForm schema=schema action=save_user}}
<fieldset>
	{{>smartInput field="name" icon="fa fa-user"}}
</fieldset>
<footer>
             <button class="btn btn-primary" type="submit">
                <i class="fa fa-save"></i>Create user
               </button>
</footer>
{{/smartForm}}
```
but i cant use invalid and invalidCount helpers in form content i trying to use
```{{#if invalid}}test{{/if}}``` and ```context.invalid``` and ```{{#with context}}```
whats i made wrong?

**Comment by jonjamz** [comment]
Did you register the form with `ReactiveForms.createForm` as in the docs?

**Comment by gibson** [comment]
yes i have a form 
```
ReactiveForms.createFormBlock({
	template: 'smartForm',
	submitType: 'normal'
});
```

**Comment by gibson** [comment]
Messages access only in form template file not in contextBlock

**Comment by jonjamz** [comment]
Can you please provide an example repo as I don't have enough information right now to diagnose the problem.

**Comment by jonjamz** [comment]
I believe that `{{#with context}}` has been broken for a while due to a Blaze update. I have fixed it in the upcoming release. I will leave this issue open just so you can verify.

**Comment by jonjamz** [comment]
I have done some more testing around this and am now confident that I can close this issue. Just note that the `context` helper is now called `formContext` in `v2.0.0`.
