### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gibson** [meteortemplates/forms#66]
Can you add option like a `isArray=true` (```{{>bsInputIcon field="phone" icon="phone" isArray=true}}```) for iterate template and collection data from template to array?

**Comment by jonjamz** [comment]
You'll have to do this in the `validationValue` function. There's no way I can reliably predict how a DOM structure will be inside someone's element, so for cases where you need special formatting, simply specify that function, get the data from the Element template as you need, form it into an array and return it for validation.
