### ISSUE TITLE
Grab reactive field value

### ISSUE THREAD

**Issue by VladShcherbin** [meteortemplates/forms#67]
Hi, how is it possible to get the reactive value from the input box?

For example, we can have a textarea and want to take the value of it, then throw to markdown block and view the changes on keyup. It is possible to do somehow now?

smth like

```handlebars
<div class="row">
  <div class="col-xs-6">
    // the input field
  </div>
  <div class="col-xs-6">
    {{#markdown}}{{fieldValue "description"}}{{/markdown}}
  </div>
</div>
```

**Comment by jonjamz** [comment]
You should be able to do this all within one Element with {{reactiveValue}}. I haven't tried it personally, but look forward to seeing how it goes for you.

**Comment by VladShcherbin** [comment]
@jonjamz I am new with this package, thinking of switching from aldeed stuff since I specify the form element. Maybe you can give me a small example?

If I understand correct, you are suggesting me to create an element with a template, holding the input box and the markdown block, am I right?

**Comment by jonjamz** [comment]
@VladShcherbin thank you for considering this package! Yes that is what I'm suggesting. In a really basic implementation, something perhaps like:

```handlebars
<template name="markdownInput">
  <textarea class="reactive-element"></textarea><br>
  {{#markdown}}{{reactiveValue}}{{/markdown}}
</template>
```

```javascript
ReactiveForms.createElement({
  template: 'markdownInput',
  validationEvent: 'keyup'
});
```

Haven't tested this, but I imagine it will work since it's all just Blaze.

**Comment by VladShcherbin** [comment]
@jonjamz yep, this is what I thought it would look like. Actually, I am now refactoring the come to use your package. I'll use this logic and write you the results when I'll finish.

Anyway, maybe you can think of making a template helper, that can somehow grab the input/textarea/etc value from the element by its name? It would be very useful and flexible to be able reactively show and update the value anywhere in the template.

**Comment by VladShcherbin** [comment]
@jonjamz okay, I've tested this solution - it works and updates well.

But:

1. There is a *validationEvent*, so on every keyup it fires the validation - I don't need that, just to output the value without validation. I tried blur, but then it won't update till blur event happens (again with validation).
2. Making such Element template is not flexible at all. If I want to show the reactive value somewhere else, I need to make a new Element and a template. This can be avoided with a Template helper and a reactive form value.

Overall, I like the package and its simplicity, but this are huge drawbacks for me. Seems like the reactive template helper without validation would solve both of them. In Autoform I had smth like:

```handlebars
<section class="widget">
  <div class="row">
    <div class="col-xs-12 col-lg-6">
      {{> afQuickField name='contents'}}
    </div>
    <div class="visible-lg col-lg-6"></div>
    <label>Превью</label>
    {{#markdown}}{{currentFieldValue "contents"}}{{/markdown}}
  </div>
</section>
```
```js
Template.registerHelper("currentFieldValue", function (fieldName) {
  return AutoForm.getFieldValue(fieldName) || null;
});
```

Maybe you have thoughts, how to make this possible ?

**Comment by jonjamz** [comment]
I've been working on a rewrite of the package that uses a named context accessible from anywhere in an app. When this is out, you'll be able to do what you want in a better way. For now, using a schema should actually be optional if you want to just skip that part altogether until the newer release comes out. The name "validationEvent" really just means "the event that triggers the handler for this element to get data into the form data context" so for your use case it's simply a bad name (and will likely change in a v2.0 release).

**Comment by VladShcherbin** [comment]
@jonjamz sure, I'll use this solution till the v2.0. Hope, it will be not far away. Thank you.
