### ISSUE TITLE
{{field}} is undocumented

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#7]
`{{field}}` is an important helper, as it allows to connect UI elements with Collection fields upon submit. However, unless I am missing something, I can't find it in the documentation...

**Comment by jonjamz** [comment]
Done! Thanks for the heads-up, and let me know if it's still not clear enough.

**Comment by steph643** [comment]
Well, what hurts me is to not see a {{field}} bullet in chapter "Element template helpers" :-)

**Comment by steph643** [comment]
Hum, 'field' is not a helper. 
Maybe a better title would be something like: "API you can use from an element's template".

**Comment by steph643** [comment]
>{{field}} is an important helper, as it allows to connect UI elements with Collection fields upon submit.

Not at all, my mistake! I didn't see that all validated form values are available from 'this' inside the action function! So there is no real need to use {{field}}...
