### ISSUE TITLE
Please put together a standalone demo in github

### ISSUE THREAD

**Issue by wesyah234** [meteortemplates/forms#70]
I'm leaving autoform and looking to this package for future form work, but I'm having trouble getting started, understanding things, etc.  You have a lot of short snippets of code but they are just not fitting all together for me such that I can bring it into my existing project.  When I was learning autoform, I put together a standalone example here: 
https://github.com/wesyah234/quickFormDemo
Is there any way you could throw together a quick demo like this one, that will actually save data to a mongo collection, edit it, create new records, with validation, etc using the simpleSchema?
Also, could you provide examples in javascript as well as coffee script, that's another roadblock to getting going with this package because some examples are only in coffee script.  Thank you very much.. this looks promising!

**Comment by jonjamz** [comment]
I'll get this together. In the meantime, please check out the revised docs coming in the next update:

https://github.com/meteortemplates/forms/tree/release/2.0.0

They should apply to the current version with the exception of the name changes noted in the History.md file on that branch.

**Comment by wesyah234** [comment]
Thanks, it would be greatly appreciated!... I did spend a lot of time today looking at the 2.0 release docs, but still can't come up with much.  For example, your first example "minimal example: check that it works" gives me a form with 2 elements, and strangely, it had 2 submit buttons and didn't do anything.  It actually reloaded the page.. so I didn't see the console.log in the console... I think this might have something to do with having to do "event.preventDefault()" I think...

**Comment by jwjames** [comment]
This works for me: edit the default submit button from within the formBlock template and remove the element template submit button.

Submit button in element template: 
https://github.com/meteortemplates/forms#using-nested-elements-for-cleaner-code

Submit button in Form Block template:
https://github.com/meteortemplates/forms#form-block-template-requirements

**Comment by jonjamz** [comment]
https://github.com/dmiskiew/meteor-templates-forms-example

One of the package users, Darek, has put together an example. I hope it will suffice. I will add it to the existing docs.

**Comment by wesyah234** [comment]
thank you!
