### ISSUE TITLE
Update validation state on field deletion

### ISSUE THREAD

**Issue by solace** [meteortemplates/forms#73]
Hi,

I'm not certain if this is an implementation error with this example or if this issue is directly related to this lib. But in reference to the example on https://meteor-templates-forms.herokuapp.com/, you can add and remove Tasks from Projects.

If there is an error in the Task field, and you delete the whole row, validation does not update, indicating the removed values are still in error, which prevents form submission.

What is the correct way of updating validation status, or forcing revalidation when fields are removed?

Thanks

**Comment by jonjamz** [comment]
All that would be required is to trigger the validation event upon removal.

**Comment by solace** [comment]
Yes, I know you didn't write it, so I want to check if it is something omitted from the documentation, or if I will need to contact the example's maintainer. :)

I thought the matter was what you said, but form submit runs validation again.  And if the schema indicates the fields are required, even if the form elements are no longer in the dom, and the data source does not contain empty references to the schema fields in question, the error still appears, and adding a new empty row shows the validation errors in place.

So that sounds as though the removed component's validation hooks are still being invoked somewhere in the form validation chain.

Could this be the case and there is something special that would need to be done to force those element's hooks to be removed?

If none of this sounds right to you, I'll refer this matter to the example's maintainer.

Thanks

**Comment by jonjamz** [comment]
I see what you mean. I think there may be a discrepancy between the way the validation is structured and the way the form elements are used. For an array of objects, I would have a single form element that allows for a variable list of form fields and returns one array of objects to be validated using `validationValue`. But after a brief look at the repository for the example, it seems it is not constructed this way. This may be the issue.

I will look at the internals of the package again, as there may be some issue with it collecting data from individual elements and not handling when they are removed. Perhaps something needs to be added to handle this in an `onDestroyed` hook in the form elements.

**Comment by solace** [comment]
Okay. Thanks for looking into this.

**Comment by davidecantini** [comment]
Hi, I'm facing the same problem described above. I also came up with the observation that even after removing a reactive-element from the DOM, its value is still returned in the submit function:
<pre><code>
.... function (els, callbacks, changed) {
  console.log("[forms] Form data!", this); // <== ISSUE: contains also the element removed from the DOM
      console.log("[forms] HTML elements with `.reactive-element` class!", els); // <== this is fine instead, does not contain the removed element.
</pre></code>
@jonjamz: your intuition about something to add in onDestroyed hook seems to be a promising solution to this problem. Do you have any update on that?
Thanks a lot for any help you can provide to fix this.

**Comment by danielparas** [comment]
@solace did you manage to find a solution to this? I have a similar issue with a form containing conditional fields that are added or deleted based on the values of other fields with the form. When deleteing a field however form fails to validate since it still checks the deleted field so to speak

**Comment by solace** [comment]
@danielparas Unfortunately I have not. Due to inactivity on this ticket/project, I actually abandoned it and have switched to autoforms, which I was hoping to avoid. :(

**Comment by danielparas** [comment]
Thanks for your reply @solace ... yeah was hoping not to go down that route either, but seems like there is no choice a this point :(

**Comment by jonjamz** [comment]
This is fixed in the latest release.
