### ISSUE TITLE
Doesn't work input type checkbox

### ISSUE THREAD

**Issue by johngonzalez** [meteortemplates/forms#77]
Hello,
Considering this:
1. In a template element inside form block I put this code:
    <input type="checkbox" class="reactive-element" value={{value}}>
2. The field is Boolean.

But the validation say me that is necessary a Boolean value. How should I get this?

**Comment by jonjamz** [comment]
Please see #74.

**Comment by johngonzalez** [comment]
Thanks for quick answer
