### ISSUE TITLE
Update others fields from a change field

### ISSUE THREAD

**Issue by johngonzalez** [meteortemplates/forms#78]
I have a array of radio buttons. I want validate each one with click event. When I click in a radio button this change property 'checked' from false to true. If I make click in other this change also to true. The problem is next:

When I make submit, the two fields now have the value true. I need that those change according with other (only a value as true).

![seleccion_004](https://cloud.githubusercontent.com/assets/12261057/9907007/b8bda170-5c52-11e5-9d00-86c3c3ec72fc.png)

My tests:
* I tried with validation Event 'change' over createElement but this dont works.
``` javascript
ReactiveForms.createElement({
  template: 'radioField',
  passThroughData: true,
  validationEvent: [ 'click', 'change' ],
  validationValue: function (el, clean, template) {

    self = this;
    // Others radio buttons make false
    $('[name=' + self.name + ']').not(this).prop('checked', false);
    // This radio button is true
    value = $(el).is(':checked');

    //Check results. Others radio buttons don't fire :(
    console.log(value);
    return value;
  },
  reset: function (el) {
    $(el).prop('checked', false);
  }
});
```
* I tried create a event helper to change others radio buttons
``` javascript
Template.radioField.events({
  'click': function (e, t){
    self = this;
    $('[name=' + self.name + ']').not(this).prop('checked', false);
    $(e.target).prop('checked', true);

    //Works, others radio buttons are checked as false. But in data submit don't :(
    $('[name=' + self.name +']').map( function () {
      console.log($(this).is(':checked'));
    });
  }
});
```
Exists a event validation 'change'?
Exists other way most simple to make things?
Thanks for collaboration

**Comment by AbdelBa** [comment]
What is the corresponding html ?

**Comment by jonjamz** [comment]
I would try using jQuery's `.trigger` across each of the unselected items to get them to register as changed. I'm not sure that changing the property like you're doing triggers that event by itself.

**Comment by jonjamz** [comment]
See this: https://forum.jquery.com/topic/should-chk-prop-checked-true-trigger-change-event

**Comment by jonjamz** [comment]
I'm closing this issue because I believe I have provided the answer. Please let me know if that is not the case.
