### ISSUE TITLE
Changing from init not working

### ISSUE THREAD

**Issue by pascajer** [meteortemplates/forms#79]
This could be a misunderstanding on my part.

If you go to http://forms-example.meteor.com/ and start typing more instead of deleting test - say make it 'test - again!'  then it stays in the init state. What's up with that?

![image](https://cloud.githubusercontent.com/assets/10549925/9932302/9f07c128-5d3a-11e5-82ea-872fc9da71df.png)

Bug or Feature?!

**Comment by jonjamz** [comment]
This has to do with the way the example is configured, and also the way the `changed` event works. In this example, the submit button is hidden until the `changed` event occurs. The `changed` event only fires when the first _valid_ change has been made in the form. The input is limited to four letters, and starts with four letters already inside it. By only adding more than four letters, you're never making a valid change. 

Probably the most confusing part of this is that the demo hides error messages on inputs until submit, but submit doesn't show until you make a valid change. So if you backspace one letter first, the `changed` event fires, and then you can proceed to add more than four letters, click the submit button, and see the error message.

I hope this makes sense. The package allows the developer to choose how they want to control all these things. Most people probably won't go this far, and the demo could certainly be made easier to understand without any internal changes in the package.

**Comment by pascajer** [comment]
Thanks dude - makes total sense :)
