### ISSUE TITLE
Feature request: a way to access all schema data of a field?

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#8]
I wanted to access the 'optional' schema attribute of a field, in order to do something like this:
```
<template name="bootstrapInput">
    <div class="reactive-input-container">
        <div class="form-group  {{#unless valid}}has-error{{/unless}}">
            <label class="control-label">{{label}}{{#unless optional}} (mandatory field){{/unless}}</label>
            ...
          </div>
    </div>
</template>
```

This made me wonder if an API to access any schema data would be possible. Ideally, from an element template, I would like to call:
```
{{schema.label}}
{{schema.instructions}}
{{schema.optional}}
{{schema.min}}
{{schema.max}}
etc.
```

**Comment by jonjamz** [comment]
I think `{{optional}}` is a good idea. It seems like a very common use case.

The other fields shouldn't be too difficult to get either. Will revisit later today.

**Comment by steph643** [comment]
Another common use case:
```
<template name="basicInput2">
  <div class="reactive-input-container">
    ...
    <input class="reactive-element" ... maxlength="{{#if schema.max}}schema.max{{/if}}">
    ...
  </div>
</template>
```

**Comment by jonjamz** [comment]
I like that.

**Comment by jonjamz** [comment]
You can do this as you've described with the `{{schema}}` helper in `1.10.0`.

**Comment by jonjamz** [comment]
Now that this exists, the `{{label}}` and `{{instructions}}` helpers could conceivably be removed for `2.0.0` resulting in a net reduction in code. What do you think?

**Comment by steph643** [comment]
Yes, I think they should be removed.

**Comment by steph643** [comment]
And maybe you could remove the `instructions` field altogether. I think it is not your package's role to add anything to simple-schema. Now that we have `{{schema}}`, people can add whatever field they want to simple-schema and use it from form elements, right?

**Comment by steph643** [comment]
`{{schema}}` does not seem to work for me in 1.10.0. It is undefined. Looking into it.

**Comment by steph643** [comment]
I confirm the above. Everything works fine (including `{{instructions}}`, `{{label}}`, and accessing the schema manually with `Template.parentData().context.schema._schema[this.field]`), except that `{{schema}}` returns undefined from within an element.

**Comment by steph643** [comment]
It works now, except for an annoying issue with {{label}}. I will post a separate issue.
Don't know what happened, it seems I wasn't in 1.10.0, strange.

**Comment by jonjamz** [comment]
Are you talking about how `{{schema.label}}` doesn't work?

I ran into that issue. Basically, Simple Schema doesn't include `label` in `_schema`.

**Comment by steph643** [comment]
I described the issue here: https://github.com/meteortemplates/forms/issues/30
