### ISSUE TITLE
Fix to allow validation of array fields as reactive elements

### ISSUE THREAD

**Issue by davidecantini** [meteortemplates/forms#80]
Hi,
Let's say we have a simple schema like this:
<pre><code>new SimpleSchema({
  emails: {
    type: [String],
    label: "Your Emails",
    regEx: SimpleSchema.RegEx.Email,
    minCount: 1,
    min: 5
  }
})</code></pre>

and the requirements would be: 
<ul>
<li>
validate each array field (email in this case) and the array to contain the required elements (the approach suggested in the comments to <a href="https://github.com/meteortemplates/forms/issues/48">issue 48</a> would not meet these requirement, since the single fields would not be reactive-elements)
</li>
<li>
the UI must enable the user to add/remove email fields through the UI (this is strictly related to <a href=https://github.com/meteortemplates/forms/issues/73>issue 73</a>)
</li>
</ul>
Can you please provide some indications/best practices on how that could be achieved? This may be about adding examples to the docs but possibly adding some features or bug fixing.

Thanks in advance for your attention.

**Comment by davidecantini** [comment]
<b>Update:</b>
For the points mentioned above, I was eventually able to add support to meet the requirements and get  an approach like the user's application linked in the package docs to work properly. 
However, that required some extra code at app level that could be completely avoided if the package could have a feature (or fix) like the one described in <a href="https://github.com/meteortemplates/forms/issues/73">issue 73</a>:

<i>"There may be some issue with it collecting data from individual elements and not handling when they are removed. Perhaps something needs to be added to handle this in an onDestroyed hook in the form elements."</i>

@jonjamz Hopefully that, or any equivalent feature that you think can achieve the same goal (i.e.  make sure that only the values of elements that have a .reactive-element class at the time of submit action are included in the valid values) can be introduced in the next versions.

With that in place, I think the package is great and would definitely star it. 

Thanks in advance.

**Comment by davidecantini** [comment]
@jonjamz Once you release version 2.0 with the modifications mentioned in issue <a href="https://github.com/meteortemplates/forms/issues/84">84</a> you can close this issue, which will get addressed by the new release. Thank you.

**Comment by jonjamz** [comment]
Thanks!
