### ISSUE TITLE
Get reactive value of a specific field in the form

### ISSUE THREAD

**Issue by danielparas** [meteortemplates/forms#83]
Hi, is there a way to get the reactive value of a specific field in the form? 

I need this as I have a `select` field which has different options based on the value selected in the field before it and I can't seem to access the form values in a reactive manner. 

I think this issue is similar to https://github.com/meteortemplates/forms/issues/67, but I can't use the solution provided by @jonjamz since only one HTML input element can be used within a form element template.

Possibly related to https://github.com/meteortemplates/forms/issues/76 also.

Any ideas if I'm missing something?

Thanks in advance!

**Comment by jonjamz** [comment]
This should be fixed in the latest release. Please see the `History.md` file for details.
