### ISSUE TITLE
this.field() in custom validation function returns undefined for value attribute

### ISSUE THREAD

**Issue by danielparas** [meteortemplates/forms#84]
Hi all, I'm trying to build a form that required password validation via password repeat/confirmation field. I'm having trouble with the custom validation for the password confirmation field as the `this.field('passwordNew').value` returns undefined constantly.

Simple schema returned is as follows:

```
   ss = new SimpleSchema({
      'passwordOld': {
        type: String,
        min: 6
      },
      'passwordNew': {
        type: String,
        min: 6
      },
      'passwordRepeat': {
        type: String,
        min: 6,
        custom: function() {
          if (this.value !== this.field('passwordNew').value) {
            return "passwordMismatch";
          }
          return true;
        }
      }
    });
```
I tried manually testing the validation to see if it's an issue with simple-schema but it is not as the validation worked fine with the following test code:

```
    ssContext = ss.namedContext("userForm")
    console.log ssContext.validate
      'passwordOld' : 'testingtesting'
      'passwordNew' : 'testtest'
      'passwordRepeat' : 'testtest'
```

This outputs `true` i.e. successful validation .. applying the same test data to the form fields results in a failed validation "passwords do not match"

Any ideas how this can be solved please?

Thanks in advance for your input! Appreciate it.

Dan

**Comment by jonjamz** [comment]
This problem is likely because under the hood `templates:forms` validates each field with `validateOne` rather than testing a group of fields with `validate`.

**Comment by danielparas** [comment]
Thanks for your response @jonjamz - much appreciated. I see, so it's not possible to validate a field based on another field? 

Before posting this issue I came across a similar issue that was filed and resolved earlier this year, issue https://github.com/meteortemplates/forms/issues/4 . The example used is exactly like what I'm trying to do and you managed to get a value for field it seems. Did you chance from `validate` to `validateOne` since then by any chance?

**Comment by jonjamz** [comment]
Ah I see your comment on that issue. Sorry I didn't respond sooner.

I have always used `validateOne` but I may have adjusted something since then and caused a regression. I will try to check it out today after work, and please feel free to bug me about it if I don't get back to you by the end of the week.

**Comment by danielparas** [comment]
Thanks for having a look @jonjamz

**Comment by danielparas** [comment]
Hi @jonjamz - did you have a look at this by any chance?

Thanks!

**Comment by danielparas** [comment]
@jonjamz bumping this again.

Thanks!

**Comment by jonjamz** [comment]
I was able to get this to work using the latest version of SimpleSchema. I didn't check against the old version, but it prevented submitting and showed the message in the appropriate place.

Screenshot: http://cloud.jonjam.es/3C1k3W0x2K2W

I'm not sure if there was a bug in the version that the package currently requires, but I will release an update tonight with the changes after I do some cleanup.

**Comment by jonjamz** [comment]
On further testing, it turns out that the result from `this.field` is indeed undefined, even in the latest version of SimpleSchema. I've been looking through SimpleSchema code and am doing more testing.

**Comment by jonjamz** [comment]
Alright, so I was finally able to fix the problem by using a named SS context instead of an unnamed one internally. I'm on a plane right now about to land, so I'll update the history and publish the latest changes once I arrive at my destination.

**Comment by davidecantini** [comment]
@jonjamz That's great news.

We're all glad to see you working on this package. Is there any chance you can provide a fix for elements removed from the DOM to not appear in the validated results? 
To quickly remind you on the possible fix you had in mind, here is an excerpt from issue <a href="https://github.com/meteortemplates/forms/issues/73"> 73</a> : <i>"I will look at the internals of the package again, as there may be some issue with it collecting data from individual elements and not handling when they are removed. Perhaps something needs to be added to handle this in an onDestroyed hook in the form elements."</i>

Thanks a lot for any update you can provide on that.

**Comment by jonjamz** [comment]
@davidecantini I just added this functionality as well and am testing now.

**Comment by davidecantini** [comment]
@jonjamz Sounds great, thank you. If you need some extra testing before releasing it I'm available now.

**Comment by danielparas** [comment]
Thats great news (for both issues!) - I will be available for testing also if you require. Thanks again @jonjamz

**Comment by danielparas** [comment]
Hey @jonjamz - when do you think you'll release the update please?

**Comment by jonjamz** [comment]
Should have this out by the 22nd at the latest. I've done a good amount of
work on the package and will be rolling it out as a `v2.0.0` with new docs
that make the changes very clear.

**Comment by jonjamz** [comment]
New version is published. I will update docs very soon. Just doing some last editing on what I had in the `release/2.0.0` branch to sync it up. Please let me know if you have any issues with the new version and I will fix them without delay.

**Comment by danielparas** [comment]
awsome @jonjamz - thanks!
