### ISSUE TITLE
v.2.1.0 Uncaught ReferenceError: ReactiveForms is not defined

### ISSUE THREAD

**Issue by davidecantini** [meteortemplates/forms#85]
Updated to version 2.1.0 and getting that exception on ReactiveForms.createElement({...});

Is there any other breaking change apart from the only one mentioned in version 2.0.0 (i.e. context => formContext)?

Please advise, thanks.

**Comment by jonjamz** [comment]
That was my mistake--in converting to JS I forgot to add the export to package.js. Please update to 2.1.1 and try again.

**Comment by davidecantini** [comment]
Yes, now the exception is gone.
I'm starting to test the new version now. While waiting for the updated docs, can you please confirm that to address the breaking change in v2.0.0, all is needed is to replace any occurrence like:
<code>{{> UI.contentBlock data=data context=context}}</code>
with 
<code>{{> UI.contentBlock data=data context=formContext}}</code>

Thanks

**Comment by jonjamz** [comment]
Oh no, you don't need to change that. The `formContext` change is just for the block helper that wraps the helpers in the actual form block invocation. For example:

```handlebars
{{#defaultFormBlock schema=schema action=action data=data}}
    {{> bootstrapInput field='username'}}

    {{#with formContext}}
      Invalid count: {{invalidCount}}, username field value: {{field 'username'}}
    {{/with}}

  {{/defaultFormBlock}}
```

**Comment by davidecantini** [comment]
Ok, got it. Thanks
