### ISSUE TITLE
Setting data in an element using JS and jQuery `trigger` is different in v.2.1.1

### ISSUE THREAD

**Issue by davidecantini** [meteortemplates/forms#86]
Let's say you have a text field whose value must be set dynamically based on other events (e.g. a hidden field where user cannot type in). Changing the hidden input value (e.g. $('#elem').val('x')) does not suffice for templates:forms to validate the value and include it into the form values in the action function.
In version 1.4 I had addressed this by triggering a validation event on the field, e.g. $('#elem').trigger('onkeyup');
With version 2.1.1 that doesn't seem to work anymore. Can you please advise if there's a better approach that can be used to address that scenario in the latest version?

Thanks

**Comment by jonjamz** [comment]
If you can give me the code you're using for this, I will test it out locally. I think the simplest way to do this is to pass the value in with the (reactive) initial data and set the option `passThroughData: true` for the hidden form element. But your method should also work.

**Comment by davidecantini** [comment]
While working on isolating the code to copy/paste here I notice that the trigger event works but with the new version I need to set the value before triggering the event. That suggests that there may be something related with the initial value of the field. I will investigate further and post an update later.
As for the other method you suggest (use passThroughData), I guess it could be useful to mention it in the new docs, I guess it's something quite common that can help others as well.
Thanks again for your prompt answers.

**Comment by davidecantini** [comment]
After fixing the initial value the field value the trigger event seems to work properly. For now let's close this issue: if I happen to notice anything unexpected I'll let you know.
Thanks.
