### ISSUE TITLE
Fields removed from the DOM still count as invalid fields!

### ISSUE THREAD

**Issue by davidecantini** [meteortemplates/forms#87]
@jonjamz: I thought this was supposed to be fixed in version 2 according to comments in issue <a href="https://github.com/meteortemplates/forms/issues/84">84</a>.

Below is a full code example for you to double check. Please follow these steps:
1) Render {{> testForm}} : one field (testField1) is visible, leave it blank
2) From the console: Session.set('includeField2', true); 
3) Two fields are now visible: leave both blank
4) Submit: you get 2 invalid fields (as expected);
5) From the console: Session.set('includeField2', false)
6) Only one field, testField1, is visible, but <b>still 2 invalid fields</b> are reported, instead of only 1 as expected (since testField2 got removed from the DOM, because of point 5).

Do you see that as an issue or it's the intended behavior? Please let me know. Thanks

Template:
<pre>
<code>
< template name="testForm">
  {{#basicFormBlock schema=schema action=action}}
    {{> basicInput schema=schema field='testField1'}}
    {{#if includeField2}}
      {{> basicInput schema=schema field='testField2'}}
    {{/if}}
  {{/basicFormBlock}}
< /template>
</code>
</pre>
Helpers:
<pre>
Template.testForm.helpers({
    includeField2: function(){
      return Session.get('includeField2');
    },
    schema: function () {
      return new SimpleSchema({
        testField1: {
          type: String,
          max: 3,
          instructions: "Enter a value!"
        },
        testField2: {
          type: String,
          max: 3,
          instructions: "Enter a value!"
        }
      });
    },
    action: function () {
      return function (els, callbacks, changed) {
        console.log("[forms] Action running!");
        console.log("[forms] Form data!", this);
        console.log("[forms] HTML elements with `.reactive-element` class!", els);
        console.log("[forms] Callbacks!", callbacks);
        console.log("[forms] Changed fields!", changed);
        callbacks.success(); // Display success message.
        callbacks.reset();   // Run each Element's custom `reset` function to clear the form.
      };
    }
  });
</pre>
Elements:
<pre>
  ReactiveForms.createFormBlock({
    template: 'basicFormBlock',
    submitType: 'normal'
  });

  ReactiveForms.createElement({
    template: 'basicInput',
    validationEvent: 'keyup',
    reset: function (el) {
      $(el).val('');
    }
  });
</pre>

Tested with version 2.1.1

**Comment by jonjamz** [comment]
Ah it's possible that I didn't re-validate without the field when it was removed. I will check it out. It shouldn't be in the form data in v2 on submit, but perhaps its validation state remains in simple schema.

**Comment by jonjamz** [comment]
I fixed this in the latest release and tested locally. It should work for you, but let me know. Thanks.

**Comment by davidecantini** [comment]
Yes, with version 2.1.2 the example above works properly. 
Thanks for fixing it immediately.
