### ISSUE TITLE
SimpleSchema defaultValue helper

### ISSUE THREAD

**Issue by 7immy** [meteortemplates/forms#93]
Can anyone tell me what the best practice is to get the SimpleSchema's defaultValue from within a FormElement. Is it `schema.defaultValue`?

Also I dont know if this is available but it would be cool to have a local helper for FormElements that has a value of the schema's defaultValue, then if data is available or the field's value has changed it will hold that value instead.

**Comment by jonjamz** [comment]
Have you tried something like:

```handlebars
{{#unless reactiveValue}}{{schema.defaultValue}}{{/unless}}
```

**Comment by 7immy** [comment]
I missed `reactiveValue`. Perfect!

**Comment by 7immy** [comment]
Not quite. 
At the moment I guess its more like this: `{{#if schema.defaultValue}}{{schema.defaultValue}}{{else}}{{value}}{{/if}}` which would allow me to use the same FormElement for both input and updating :) Unfortunately its a bit long for my taste :)

This registerHelper below seems to work well for me:  {{defaultValueUnlessData}}

```
Template.registerHelper('defaultValueUnlessData', function(val){
    let ti = Template.instance(), defaultVal =  ti.reactiveForms.schema.schema(ti.data.field).defaultValue
    return defaultVal || ti.reactiveForms.initValue;
});
```
