### ISSUE TITLE
Validate elements before submission

### ISSUE THREAD

**Issue by ramijarrar** [meteortemplates/forms#94]
Following #89

Form elements are not currently validated on submission, this can lead to difficult issues where outdated values are passed into the form action. There is currently no straightforward way to workaround this, since the 'submit' event is only triggered on the form block and that 'validate' method does not pull values from the DOM.

(Also I don't think this should be implemented as an option, values passed into 'action' should always correspond to what is actually in the input)

**Comment by jonjamz** [comment]
If you would like to add an option to do one more round of data collection and validation on submission, that is fine with me and I would add it into the core. Would you be willing to submit a PR for this?

**Comment by jonjamz** [comment]
Just out of curiosity, what is the issue you're having with collecting data using events triggered on the elements?

**Comment by ramijarrar** [comment]
There are a few edge cases, like for example after auto-completion (no 'keyup' or 'changed' events are triggered) but also a lot of the forms that I use have little restrictions (not more than one error per field) and so it doesn't make sense to do any validation before submit.

In all cases, I think it is a fair assumption that the data going into the form action is up to date and I don't think there is any use case for submitting data that is no longer current.

**Comment by ramijarrar** [comment]
To expand on the second case, very often validation boils down to 'the field is required' and max/min for exceptional cases. Running that on 'keyup' or changed is not only excessive but can also create a poor user experience.

**Comment by ramijarrar** [comment]
And consider cases where you want to throttle validation, you want to be sure that after a few quick keystrokes we can still get the current data in the form action.

**Comment by ramijarrar** [comment]
I think it is generally a fair assumption that the data going into the form action will be up-to-date.

**Comment by davidecantini** [comment]
@ramijarrar:
- I agree with you when you say "values passed into 'action' should always correspond to what is actually in the input". That seems to be obvious but it's actually not the case, as you noticed.
- At the same time, I'm not so convinced when you say "Running that every time the value changes is not only excessive but also just poor UX". Without making any assumption on how an application intends to use it, what validation event are you using? Have you tried "blur" instead of "keyup" for example? That would be enough to avoid validating on each key stroke.

**Comment by jonjamz** [comment]
Right, I would say the UX of immediate feedback as you work with the form is better. Also if your form changes based on what the user has entered, it's important to collect the data as they are filling it in.

**Comment by jonjamz** [comment]
A large part of the mission of this package is to allow users to create reactive forms. That is why data is collected and processed at the time it is entered. If you want to disable that because your form elements have expensive DOM reads that should be an option, but in practice I have never seen noticeable performance issues in my own use of the package. And of course that last round of collection and validation on submission will be added either by me or someone else's PR.

**Comment by ramijarrar** [comment]
@davidecantini I don't think there is any disagreement here, 'blur' would be an example of not validating on every change which is not currently possible.

@jomjamz My point about throttling validation was only to provide an example of when "collecting data using events triggered on the elements" would be unreliable. There are many other cases that could be mentioned here (password/identity managers, native auto-fill features) but I think we are mostly in agreement. If you don't have the bandwidth for this at the moment, I would be happy to work on a PR.

**Comment by davidecantini** [comment]
@ramijarrar: "'blur' would be an example of not validating on every change which is not currently possible" 
I agree with the first part of your statement, but not with the second part. Are you aware that you can specify the validation event? In particular you can specify "blur".

**Comment by ramijarrar** [comment]
@davidecantini It's not currently possible within the context of this issue. I agree

**Comment by jonjamz** [comment]
@ramijarrar I would greatly appreciate help with a PR for this. I just started a new position yesterday so I'm playing catch-up for the next week or so.

**Comment by ramijarrar** [comment]
@jonjamz I was planning to spend some more time on this Friday/Saturday, I'll file a PR as soon as I have something working.

**Comment by davidecantini** [comment]
@ramijarrar:
Thank you for your comment. Just to summarize, reading this thread I see two points: 

a) Your statement: "...very often the validation you are doing boils down to 'the field is required' and say max/min for exceptional cases. Running that every time the value changes is not only excessive but also just poor UX". My point here was to suggest that if one doesn't like/want to validate every time, can validate on blur for example. No change required to the library here.

b) the title of the issue "Validate elements before submission", correctly supported by your statement "...values passed into 'action' should always correspond to what is actually in the input".  That is, validating all the fields at submission time. As I say in my initial comment, this should be implemented.

@jonjamz: can you please confirm that b) is what is going to be addressed by the PR?

Thank you guys

**Comment by ramijarrar** [comment]
@davidecantini Those are not separate points, the issue has always been about adding a final round of validation before submit and that is what will be addressed in the PR. We were discussing cases where the current functionality (of validating only inside elements) would be insufficient. Essentially any form which does not validate on every change, e.g only on submit or on blur as you suggested, is vulnerable to inconsistencies between the values in the form and what is passed to the form action. That mean this is a valid concern (of which we are all in agreement) but not that there is anything wrong with the implementation of validation events.

I hope that clears things up :)
